### ISSUE TITLE
Выстроить RoadMap и продумать идею

### ISSUE THREAD

**Issue by WhiteHodok** [GigaOrg/GigaAsessor#2]

**Comment by WhiteHodok** [comment]
![image](https://user-images.githubusercontent.com/39564937/236613925-1e0e2294-6a30-4edb-86c5-aec282af5b1e.png)

**Comment by WhiteHodok** [comment]
RoadMap:
1.Написать функционал для телеграм бота на основе aiogram библиотеки:
-Реализовать команду /start для запуска бота
-Реализовать обработку сообщений с промптами от пользователей
-Реализовать функционал для отправки промпта на обработку через OpenAI API
-Реализовать ответ бота с рекомендациями по улучшению промпта

2.Написать функционал для дискорд бота на основе discord библиотеки на python:
-Реализовать команду !start для запуска бота
-Реализовать обработку сообщений с промптомами от пользователей
-Реализовать функционал для отправки промпта на обработку через OpenAI API
-Реализовать ответ бота с рекомендациями по улучшению промпта

3.Создать back-end сервер на node.js и Flask:
-Реализовать API для обмена данными между ботами и сервером
-Реализовать хранение промптов и рекомендаций на сервере

4.Создать front-end сайт:
-Реализовать дизайн сайта
-Разместить на сайте информацию о ботах, их использовании и функционале
-Добавить ссылки на телеграм и дискорд ботов

5.Интегрировать OpenAI API:
-Получить API-ключи от OpenAI
-Реализовать функционал отправки промпта на обработку через OpenAI API
-Реализовать функционал получения рекомендаций от OpenAI API

6.Тестирование и деплой:
-Провести тестирование всех компонентов
-Развернуть сервер на хостинге
-Деплоить ботов на телеграм и дискорд платформы

**Comment by slenderik** [comment]
Цели:
- слеш команда оценки
- ивент @Клайд
- ивент ветки с Клайдом

**Comment by WhiteHodok** [comment]
our jobstory:
Конечный пользователь: человек, который хочет улучшить свои запросы для использования искусственного интеллекта.
Ситуация: пользователь часто работает с искусственным интеллектом, но его запросы не всегда дают желаемый результат. Он хочет улучшить свои запросы, чтобы получить лучшие результаты.
Задача: найти эффективный способ составления промптов для использования с искусственным интеллектом.
Решение: пользователь использует бота, который основан на GPT-3.5. Бот помогает пользователю составлять промпты, которые максимально точно описывают его запросы, и даёт советы по их улучшению. Пользователь может оценить промпт бота и получить ответ на свой вопрос.
Результат: пользователь получает более точные и эффективные запросы, которые позволяют использовать искусственный интеллект более эффективно. Он увеличивает свою продуктивность и экономит время, используя бота для составления промптов.

**Comment by WhiteHodok** [comment]
User Story : 
Конечный пользователь хочет использовать бота, который помогает в составлении промптов для использования с искусственным интеллектом. Пользователь хочет, чтобы бот был доступен через Telegram и мог предоставлять советы по улучшению запросов, которые пользователь отправляет. Кроме того, пользователь хотел бы иметь возможность оценить промпт, чтобы получить дальнейшие советы. Бот также должен хранить информацию об оценке пользователя для использования в будущих запросах. Пользователь предпочел бы, чтобы бот использовал легкоиспользуемую базу данных для хранения информации о запросах и оценках, и хотел бы, чтобы это было реализовано без необходимости написания большого количества кода.

**Comment by WhiteHodok** [comment]
User Expirience:
Конечный пользователь будет иметь положительный опыт использования нашего бота, так как он сможет быстро и легко составить запрос для искусственного интеллекта, который будет нацелен на определенную тему. Бот будет предлагать пользователю поправки и дополнения к запросу, чтобы улучшить его качество и точность. Пользователь будет иметь возможность давать обратную связь на запросы, чтобы помочь улучшить качество работы бота в будущем. Кроме того, мы собираемся использовать базу данных для сохранения запросов и обратной связи пользователей, что поможет улучшить работу бота с течением времени. В целом, пользователи будут получать быстрый и качественный опыт использования нашего бота.

**Comment by WhiteHodok** [comment]
Формат БД:
![image](https://user-images.githubusercontent.com/39564937/236670582-007cc26c-cea1-4c7a-a3d4-c50a748a2090.png)
